version: '3.7'
services:

  # ngrok:
  #   container_name: ocean_jobs_ngrok
  #   image: wernight/ngrok
  #   ports:
  #     - 4040:4040
  #   links:
  #     - lambda
  #   environment:
  #     - NGROK_PROTOCOL=http
  #     - NGROK_PORT=app:5000
  #     - NGROK_AUTH=${NGROK_AUTH}

  lambda:
    container_name: ocean_jobs_lambda_5000
    image: lambci/lambda:build-python3.7
    ports:
      - 5000:5000
      - 9001:9001
    env_file: config/.env.dev
    environment:
      - DOCKER_LAMBDA_STAY_OPEN=${AWS_LAMBDA_STAY_OPEN}
    volumes:
      - layer:/var/lang
      - lambda:/var/task
      - ./:/srv
    working_dir: /srv
    command: /bin/bash -c "pip install -r src/requirements-dev.txt && pip install -e src/."

volumes:
  lambda:
  layer: